/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * QUAL-29: the invariant, language-neutral core of a handler donation. Holds the method list and the ParameterSpec core (name/type/required/choices=canonical/min-max/pattern/entity_type) plus the per-method room_context. Per-language phrasing lives in the sibling <lang>.json files.
 */
export interface IreneIntentDonationLanguageNeutralContractV11 {
  $schema?: string;
  schema_version: "1.1";
  donation_version?: string;
  /**
   * Canonical, language-neutral domain key (ASCII; must match the intent_name_patterns prefix).
   */
  handler_domain: string;
  description?: string;
  intent_name_patterns?: string[];
  domain_patterns?: string[];
  fallback_conditions?: {}[];
  action_domain_priority?: number;
  /**
   * @minItems 1
   */
  method_donations: [Method, ...Method[]];
  global_parameters?: Param[];
  [k: string]: unknown;
}
export interface Method {
  method_name: string;
  intent_suffix: string;
  boost?: number;
  room_context?: "required" | "none" | "conditional";
  parameters?: Param[];
}
export interface Param {
  name: string;
  type: "string" | "integer" | "float" | "datetime" | "boolean" | "choice" | "entity";
  required?: boolean;
  /**
   * Canonical (language-neutral) choice tokens; per-language spoken forms live in <lang>.json choice_surfaces.
   */
  choices?: string[] | null;
  min_value?: number | null;
  max_value?: number | null;
  pattern?: string | null;
  entity_type?: "device" | "location" | "room" | "person" | "generic";
}
